# Generated by Django 3.2.5 on 2022-11-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={},
        ),
    ]
