# Generated by Django 3.2.5 on 2022-11-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='party_abbreviation',
            field=models.CharField(max_length=7),
        ),
    ]
