# Generated by Django 3.2.5 on 2022-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_announcedpuresults_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='party_abbreviation',
            field=models.CharField(max_length=7),
        ),
    ]
