# Generated by Django 3.2.5 on 2022-11-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20221120_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='agentname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcedlgaresults',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcedpuresults',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcedstateresults',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcedwardresults',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pollingunit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={},
        ),
    ]
